Initial header changes
City-of-Turku/linkedevents-ui pull request #199
Opened 2020-12-31 12:26 UTC by Ducky07

Removed double nav from header.
Now the other one is just a banner. (At least according to NVDA)
Removed some old deprecated stylings and updated localization texts.

Logout now reads 'Clickable submenu. User, (username) Menu' (Considering changing it to just '... User, (username) since it already mentions that it's a submenu)

Might still require more tests.

2020-12-31 12:32 UTC, Ducky07 commented
Reviewing this again on Monday. Wait until then.

2021-01-05 05:24 UTC, aceViilee approved these changes

2021-01-05 05:25 UTC, aceViilee requested changes
Build fail

2021-01-05 09:29 UTC, aceViilee approved these changes

2021-01-05 11:11 UTC, merged