Allow user to switch between his/her organizations
City-of-Turku/linkedevents-ui pull request #380
Opened 2022-12-27 14:16 UTC by awel1122

# Allow user to switch between his/her organizations

## changes
    - allows user to be able to switch between organizations it belongs
    - changes user permissions according to selected organization for the user

### [Trello card #382](https://trello.com/c/5Wux5OQc/382-frontend-as-user-of-multiple-organizations-i-want-to-change-organization-and-permissions)

-----------------------------------------------------------------------------------------------
### Breakdown:

#### Kategoria-otsikko
 1. Tiedosto 
     * Selitys muutoksista
   
 2. Tiedosto
     * Selitys muutoksista
    
 3. Tiedosto
     * Selitys muutoksista
     
#### Kategoria-otsikko
 1. Tiedosto 
     * Selitys muutoksista
   
 2. Tiedosto
     * Selitys muutoksista
    
 3. Tiedosto
      * Selitys muutoksista

2023-01-03 07:34 UTC, hienous requested changes
observations/findings should be viewable in this gist. https://gist.github.com/hienous/4b75312bc70f2f4bbc97d44049942ad3

2023-01-03 14:39 UTC, awel1122 commented
> observations/findings should be viewable in this gist. https://gist.github.com/hienous/4b75312bc70f2f4bbc97d44049942ad3
![fetch_all_organizations](https://user-images.githubusercontent.com/117433931/210378850-9f42f472-ea1e-45be-a301-bbf97a1373ec.gif)

Fixed as follows. Backend change contains pagination-class which will send 1000 pages (if available) and with that we don't need to changed organization fetching logic in frontend.

2023-01-04 08:15 UTC, hienous requested changes

2023-01-04 08:15 UTC, hienous commented on src/components/Header/ActiveOrganizationSelector.js
> +
If the user only belongs to one organization -> the actual html isn't being rendered but the event listener is still set which causes errors when clicking anywhere on the site. Maybe the event listener should only be added if there are more than 1 organizations.
![image](https://user-images.githubusercontent.com/50320115/210511203-4c83998f-9444-4361-aae5-5640c124044e.png)

2023-01-04 10:14 UTC, awel1122 commented on src/components/Header/ActiveOrganizationSelector.js
> +
Fixed.

2023-01-04 11:38 UTC, hienous approved these changes

2023-01-04 12:09 UTC, merged